apiVersion: v1
kind: Secret
metadata:
  name: app
stringData:
  POSTGRES_USER: pguser
  POSTGRES_PASSWORD: pgsecret
  POSTGRES_DB: app
  DATABASE_URL: postgresql+psycopg://pguser:pgsecret@postgres:5432/app
  SECRET_KEY: secretkey
